API extensions
frab/frab pull request #871
Opened 2021-11-09 08:59 UTC by saerdnaer

This PR adds:
* schedule.json/.xml: Room guid's #507
* schedule.json/.xml: Person guid based on hashed emails using NS_URL with acct:user@domain.tld simular to webfinger
* internal JSON API: more person attributes for orga
* deprecates `person.full_name`, recommending `person.name` in all JSON APIs

2021-11-14 13:24 UTC, manno approved these changes

2021-11-14 15:02 UTC, manno requested changes
Tests are failing

2021-11-18 19:21 UTC, saerdnaer commented
@manno Rebased onto main and fixed tests.

2021-11-21 14:59 UTC, manno approved these changes

2021-11-21 14:59 UTC, merged